version: "3.1"

services:
  db:
    container_name: quickjournal-db
    image: postgres:15
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: quickjournal
    volumes:
      - quickjournal_db:/var/lib/postgresql/data
volumes:
  quickjournal_db:
